name: unimastery_mobile
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.5
  equatable: ^2.0.5
  flutter_keyboard_visibility: ^5.4.0
  sms_autofill: ^2.2.0
  animations: ^2.0.7
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  readmore: ^2.2.0
  uni_links: ^0.5.1
  video_player: ^2.4.7
  video_thumbnail: ^0.5.3
  firebase_crashlytics: ^3.0.5
  firebase_core: ^2.2.0
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  file_picker: ^5.2.2
  share_plus: ^6.3.0

  intl: ^0.17.0
  dropdown_button2:
    git:
      url: https://github.com/ali-almas/dropdown_button2.git
      ref: master
  provider: ^6.0.4
  chewie: ^1.3.5
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.1.10
  retrofit: ^4.0.1
  dio: ^5.1.1



dev_dependencies:
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: any

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/fonts/
   - assets/images/
   - assets/dummy/
   - assets/icons/